### ISSUE TITLE
Missing predict function

### ISSUE THREAD

**Issue by dariomasante** [hojsgaard/gRain#2]
predict function (predict.grain) is not exported to namespace, therefore it is not available to users, despite being documented in the manual (and accessible through the operator ::: ).

**Comment by Issoufou-Liman** [comment]
There is also nodeNames function that is no longer accessible for the same reason raised by @dariomasante. Another important change I noticed is the name of the class 'CPTgrain' which now becomes 'cpt_grain'. Many things are broken in my code with this version :). What are the good reasons for these changes?

**Comment by hojsgaard** [comment]
nodeNames is unfortunately not exported for the moment. My fault. I am waiting for packages to be updated on CRAN.

Regarding CPTgrain vs cpt_grain: It is better to invoke generic functions rather than specific methods. If you stick to generic functions, what you write about is no longer an issue.
